using Microsoft.AspNetCore.Http.Json;
using System.Drawing.Printing;
using ZPv2.Common.Models;
using ZPv2.Common.Printing;
using ZPv2.Common.System;

var builder = WebApplication.CreateBuilder(args);

builder.Host.UseWindowsService(options =>
{
    options.ServiceName = "ZPv2Service";
});

builder.WebHost.UseUrls("http://127.0.0.1:16262");

builder.Services.Configure<JsonOptions>(options =>
{
    options.SerializerOptions.PropertyNamingPolicy = System.Text.Json.JsonNamingPolicy.CamelCase;
    options.SerializerOptions.WriteIndented = false;
});

builder.Services.AddSingleton<FileLog>();
builder.Services.AddSingleton<JsonConfigStore>();
builder.Services.AddSingleton<EscPosRenderer>();
builder.Services.AddSingleton<RawPrinterTransport>();

var app = builder.Build();

var log = app.Services.GetRequiredService<FileLog>();
var store = app.Services.GetRequiredService<JsonConfigStore>();
var cfg = store.GetOrCreate();
log.Info("ZPv2 service booting on 127.0.0.1:16262. Logs=" + log.LogDir);

app.Use(async (context, next) =>
{
    if (!IsLoopback(context.Connection.RemoteIpAddress))
    {
        context.Response.StatusCode = StatusCodes.Status403Forbidden;
        await context.Response.WriteAsJsonAsync(new { ok = false, error = "Only localhost is allowed." });
        return;
    }
    await next();
});

app.Use(async (context, next) =>
{
    context.Response.Headers["Access-Control-Allow-Origin"] = "*";
    context.Response.Headers["Access-Control-Allow-Methods"] = "GET,POST,OPTIONS";
    context.Response.Headers["Access-Control-Allow-Headers"] = "Content-Type,X-ZPV2-TOKEN,X-ZALDO-TOKEN,X-PRINTER-NAME,X-PRINTER-ID";

    if (HttpMethods.IsOptions(context.Request.Method))
    {
        context.Response.StatusCode = StatusCodes.Status204NoContent;
        return;
    }

    await next();
});

app.Use(async (context, next) =>
{
    if (context.Request.Path.Equals("/health", StringComparison.OrdinalIgnoreCase)
        && HttpMethods.IsGet(context.Request.Method))
    {
        await next();
        return;
    }

    var config = store.GetOrCreate();
    var token = context.Request.Headers["X-ZPV2-TOKEN"].ToString().Trim();
    if (string.IsNullOrWhiteSpace(token))
    {
        token = context.Request.Headers["X-ZALDO-TOKEN"].ToString().Trim();
    }

    if (!TokenService.IsValid(token) || !string.Equals(token, config.Token, StringComparison.Ordinal))
    {
        context.Response.StatusCode = StatusCodes.Status401Unauthorized;
        await context.Response.WriteAsJsonAsync(new { ok = false, error = "Token inválido do ZPv2." });
        return;
    }

    await next();
});

app.MapGet("/health", (JsonConfigStore configStore) =>
{
    var config = configStore.GetOrCreate();
    var tokenSuffix = config.Token.Length >= 4 ? config.Token[^4..] : config.Token;
    var printers = ListInstalledPrinters();
    return Results.Ok(new
    {
        ok = true,
        app = "ZPv2",
        service = "ZPv2Service",
        version = "2.0.0",
        listening = "127.0.0.1:16262",
        status = "online",
        token_masked = "************" + tokenSuffix,
        printersConfigured = printers.Count,
        pendingByPrinter = new Dictionary<string, int>(),
        now = DateTimeOffset.Now,
    });
});

app.MapGet("/printers", () =>
{
    var printers = ListInstalledPrinters()
        .Select((name) => new { id = name, name })
        .ToArray();
    return Results.Ok(new
    {
        ok = true,
        configured = printers,
    });
});

app.MapGet("/token", (JsonConfigStore configStore) =>
{
    var config = configStore.GetOrCreate();
    return Results.Ok(new
    {
        ok = true,
        token = config.Token,
    });
});

app.MapPost("/token/regenerate", (JsonConfigStore configStore, FileLog logger) =>
{
    var token = configStore.RegenerateToken();
    logger.Warn("Token regenerated by local request.");
    return Results.Ok(new { ok = true, token });
});

app.MapPost("/print", (HttpContext context, PrintJobRequest request, EscPosRenderer renderer, RawPrinterTransport transport, FileLog logger) =>
{
    var printerName = (request.PrinterName ?? string.Empty).Trim();
    if (string.IsNullOrWhiteSpace(printerName))
    {
        printerName = context.Request.Headers["X-PRINTER-NAME"].ToString().Trim();
    }
    if (string.IsNullOrWhiteSpace(printerName))
    {
        printerName = context.Request.Headers["X-PRINTER-ID"].ToString().Trim();
    }

    if (string.IsNullOrWhiteSpace(printerName))
    {
        return Results.UnprocessableEntity(new { ok = false, error = "Nome da impressora não informado no pedido." });
    }

    byte[] bytes;
    try
    {
        bytes = renderer.Build(request);
    }
    catch (Exception ex)
    {
        logger.Error("Failed to build ESC/POS payload.", ex);
        return Results.UnprocessableEntity(new { ok = false, error = "Não foi possível preparar o job de impressão." });
    }

    var result = transport.Send(printerName, bytes, "ZPv2 " + (request.Type ?? "RECEIPT"));
    if (!result.Ok)
    {
        logger.Error("Print failed on printer '" + printerName + "': " + result.Message);
        return Results.UnprocessableEntity(new { ok = false, error = result.Message, printer = printerName });
    }

    logger.Info("Print success on printer='" + printerName + "' type='" + (request.Type ?? "RECEIPT") + "'");
    return Results.Ok(new { ok = true, message = result.Message, printer = printerName });
});

app.Run();

static bool IsLoopback(System.Net.IPAddress? ip)
{
    if (ip is null) return false;
    return System.Net.IPAddress.IsLoopback(ip);
}

static List<string> ListInstalledPrinters()
{
    var printers = new List<string>();
    try
    {
        foreach (string printer in PrinterSettings.InstalledPrinters)
        {
            var name = (printer ?? string.Empty).Trim();
            if (name.Length == 0)
            {
                continue;
            }
            if (!printers.Contains(name, StringComparer.OrdinalIgnoreCase))
            {
                printers.Add(name);
            }
        }
        printers.Sort(StringComparer.CurrentCultureIgnoreCase);
    }
    catch
    {
        // Mantém retorno vazio em ambientes sem spooler inicializado.
    }

    return printers;
}
